// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reinmar.DA.DataAccess;

namespace Reinmar.DA.Migrations
{
    [DbContext(typeof(ReinmarDbContext))]
    [Migration("20190522165352_UpdatedSchema")]
    partial class UpdatedSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reinmar.DA.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CashOnDelivery");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("HouseNumber");

                    b.Property<string>("Notes");

                    b.Property<string>("OrderName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode");

                    b.Property<string>("ReceiverEmail");

                    b.Property<string>("ReceiverFullName");

                    b.Property<Guid>("SenderId");

                    b.Property<string>("SitId");

                    b.Property<string>("StreetName");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Reinmar.DA.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Event");

                    b.Property<string>("Location");

                    b.Property<Guid?>("PackageId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Reinmar.DA.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Reinmar.DA.Models.Status", b =>
                {
                    b.HasOne("Reinmar.DA.Models.Package", "Package")
                        .WithMany("Statuses")
                        .HasForeignKey("PackageId");
                });
#pragma warning restore 612, 618
        }
    }
}
